os: Visual Studio 2017

platform:
  - x64

branches:
  only:
    - /master|^v\d+\.\d+\.\d+(-.*)?$/

install:
  # https://www.appveyor.com/docs/lang/nodejs-iojs/#installing-any-version-of-nodejs-or-iojs
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild 12) $env:PLATFORM
  - yarn install --force

build_script:
  - yarn check-prettier
  - yarn build
  - ./script/test-appveyor.bat
  - yarn prebuild-node
  - yarn prebuild-node-ia32
  - yarn prebuild-electron
  - yarn prebuild-electron-ia32
  - if defined APPVEYOR_REPO_TAG_NAME (npm run upload)

test: off
deploy: off
